language: java
dist: trusty
sudo: required
jdk:
- oraclejdk8
env:
  global:
  - secure: DbveaxDMtEP+/Er6ktKCP+P42uDU8xXWRBlVGaqVNU3muaRmmZtj8ngAARxfzY0f9amlJlCavqkEIAumQl9BYKPWIra28ylsLNbzAoCIi8alf9WLgddKwVWsTcZo9+UYocuY6UivJVkofycfFJ1blw/83dWMG0/TiW6s/SrwoDw=
  - >-
    APP_CONFIG="config.TestingConfig" PATH=$PATH:${HOME}/google-cloud-sdk/bin
    CLOUDSDK_CORE_DISABLE_PROMPTS=1
script:
- gradle assemble
- gradle clean
before_script:
- pip install --user codecov
install: true
after_success:
- if [ -e ./gradlew ]; then ./gradlew test jacocoTestReport;else gradle test jacocoTestReport;fi
- bash <(curl -s https://codecov.io/bash)
- bash kubernetes/travis/deploy.sh
- codecov